#inspired by https://pynative.com/python-range-function/
'''syntax of the range() function: 
range(start, stop[, step])
It takes three arguments. Out of the three, two are optional. The start and step are optional arguments and the stop is the mandatory argument.
start - optional  argument, default value is 0 if not specified.
step - optional  argument. Specify the increment value. Each next number in the sequence is generated by adding the step value to a preceding number. 
    The default value is 1 if not specified. It is nothing but a difference between each number in the result. 
    For example, range(0, 6, 1) - where step = 1.
stop - mandatory argument, range() never includes the stop number in its result'''

#Return Value of range() is the object of class range. for example:
print(type(range(10)))
# Output: <class 'range'>

# Generate numbers between 0 to 6
for i in range(6): #where 6 is mandatory argument stop
    print(i)
'''
Output:
0
1
2
3
4
5
'''


